#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# on-boot programs
xset s off 
xset s noblank
xset -dpms
nitrogen --restore &
picom -m 1 -i 1 &
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

# Window Config
bspc config border_width            2
bspc config window_gap              8
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config top_monocle_padding     8
