#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# on-boot programs
xset s off 
xset s noblank
xset -dpms
nitrogen --restore &
picom -m 1 -i 1 &
xsetroot -cursor_name left_ptr

# polybar start
bspc monitor -d 1 2 3 4 5
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar main &

# colors
bspc config normal_border_color     '#0906180'
bspc config active_border_color     '#c0a36e'
bspc config focused_border_color    '#c0a36e'
bspc config presel_feedback_color   '#c0a36e'

# Window Config
bspc config border_width            2
bspc config window_gap              8
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config top_monocle_padding     8
